### ISSUE TITLE
Journée porte ouvertes - 23 octobre

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/labouvroir#192]

**Comment by lenaMK** [comment]
soit le 13 en après-midi (après le midi-causerie de JP Fourmentraux), soit une autre journée la semaine suivante (exemple mercredi 20 septembre)

**Comment by lenaMK** [comment]
Date à sélectionner quand on aura la date de livraison du mobilier!

**Comment by lenaMK** [comment]
Lundi 23 octobre de 13h à 17h!

**Comment by lenaMK** [comment]
Format de présentation: 
- Titre 
- Nom 
- Technologies
- Mots-clés 

Exemple: 

```YAML
Titre : Autour des réseaux d’artistes-thèmes dans les critiques d’art publiées par cinq revues numériques au Brésil
Nom : Talitha Motter
Technologies : TEI-XML, XQuery, GraphML, Cytoscape
Mots-clés : Brésil, Art actuel, Revues d’art numériques, Critique d’art, Réseaux

```

[Tests pour le visuel](https://www.canva.com/design/DAFvAfbxqoc/zQqQb9f_jNikDwHm9tRf3Q/view?utm_content=DAFvAfbxqoc&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)

**Comment by LeaMaronet** [comment]
```YAML
Titre : Visualiser des motifs animaliers et végétaux dans les sculptures produites en Inde ancienne
Nom : Léa Maronet
Technologies : Python, intelligence artificielle
Mots-clés : Inde, sculpture, iconographie, vision par ordinateur, bouddhisme, jaïnisme, brahmanisme 

```

**Comment by altrc** [comment]
Titre : La critique mise en page : segmenter une revue d’art des années soixante
Nom : Alice Truc
Technologies : LayoutParser, Python, computer vision
Mots-clés : revues, critique d’art, art contemporain, segmentation, OCR/OLR, graphisme

**Comment by CamilleDelattre** [comment]
```YAML
À la recherche de 750 artistes dans Wikidata: réconciliation de données dans le web sémantique
Nom : Camille Delattre, avec l'équipe de la Maison MONA Julie Graff, Lena Krause, Alexia Pinto Ferretti, Simon Janssen
Technologies : LOD, OpenRefine
Mots-clés : art public, wikidata, Web sémantique, données culturelles, Québec
```

**Comment by lenaMK** [comment]
@WilliamDiakite & @emchateau  pour la présentation du labo par William, je proposececi, auriez-vous des technologies ou mot-clefs à rajouter qui de façon générale présentent le travail et les projets principaux du labo? 

Titre: Présentation du laboratoire Ouvroir
Nom : William Diakité, avec Lena Krause, Emmanuel Château-Dutier et Kristine Tanton
Technologies : svelte, IIIF, web components, LOD,  photogrammétrie
Mots-clés : histoire de l'art numérique, muséologie numérique, 3D, web sémantique

@emchateau et @valentinehda je n'ai pas encore reçu vos descriptions. Idéalement j'en aurais besoin pour ce matin mais sinon d'ici mercredi matin svp comme ça je peux terminer ça mercredi, merci!

**Comment by valentinehda** [comment]
```YAML
Titre : L'entrée des femmes artistes dans la collection du MAC (1964-2020)
Nom : Lena MK et Valentine Desmorat 
Technologies : Observable, notebooks, visualisation de données
Mots-clés : JavaScript, web, études féministes, méthode quantitative, CIÉCO
```
